repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: npm-lint
        name: npm run lint
        entry: npm run lint
        language: system
        pass_filenames: false
